### ISSUE TITLE
📜 List coordinators per WP

### ISSUE THREAD

**Issue by prudhomm** [numpex/exama#14]
Create the list for coordinators and setup the todo list for #13

**Comment by FredericN** [comment]
C'est ok pour moi d'ajouter Luc Giraud et Vincent Faucher aux responsables du WP3.

**Comment by Ghaztal** [comment]
Ok pour moi. je préfère rajouter un suppl. sur la partie shape (Y. Privat).
bien cdt

**Comment by josselingarnier** [comment]
C'est OK pour mettre Amandine Marrel au WP6.

**Comment by markasch** [comment]
C'est bon pour WP4 (Arthur comme suppléant)
