### ISSUE TITLE
📜 List coordinator per Partner

### ISSUE THREAD

**Issue by prudhomm** [numpex/exama#15]
- CEA: Isabelle Ramière, Vincent Faucher
- EP: Josselin Garnier
- INRIA: Hélène Barucq, Luc Giraud
- Sorbonne Université : Stéphane Labbé, Pierre Jolivet
- Unistra: Christophe Prud'homme, Emmanuel Franck

**Comment by iramiere** [comment]
Rajouter Vincent Faucher pour le CEA

**Comment by prudhomm** [comment]
@iramiere il faudra alors mettre de l'implication de vincent dans le WP0
