### ISSUE TITLE
fill administrative information in financial annex

### ISSUE THREAD

**Issue by prudhomm** [numpex/exama#25]
Merci de remplir les onglets suivants jusqu'à la ligne 28 de l'annexe financière https://docs.google.com/spreadsheets/d/1YErnlRpFtLqYbrTer5Wur6-v4xjteSmq/edit?usp=sharing&ouid=109146539207877795266&rtpof=true&sd=true

- Part2: CEA
- Part3: Ecole Polytechnique
- Part3: INRIA
- Part4: Sorbonne Université

**Comment by prj-** [comment]
The form has been sent today for SU. @prudhomm, I'm seeing `Part3` is appearing twice here. I filled the sheet `Part4` in the `.xlsx`, but you may want to move that to `Part5`. Sorry for the noise.
