### ISSUE TITLE
add colleagues implication

### ISSUE THREAD

**Issue by prudhomm** [numpex/exama#28]
Edit partner sheet and add colleagues implication as a percentage in the columns WP0 to WP7

https://docs.google.com/spreadsheets/d/1pQ7TQING8fBV9Ig1bqz4J6nuMcHVp71XJAMbly0XHyE/edit#gid=0

⚠️ pour les enseignants chercheurs mettre le temps d'implication sur le **temps de recherche** (donc pas le temps complet)

**Comment by prj-** [comment]
The form is filled for SU.
